//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Detalle_dev_compra
    {
        public int Id_devolucion { get; set; }
        public string Cod_producto { get; set; }
        public string Motivo { get; set; }
        public int Cantidad_devuelta { get; set; }
        public double sub_Total { get; set; }
    
        public virtual Producto Producto { get; set; }
        public virtual Devolucion_Compra Devolucion_Compra { get; set; }
    }
}
