//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Producto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Producto()
        {
            this.Detalle_Compra = new HashSet<Detalle_Compra>();
            this.Detalle_dev_compra = new HashSet<Detalle_dev_compra>();
            this.Detalle_Venta = new HashSet<Detalle_Venta>();
        }
    
        public string CodigoProducto { get; set; }
        public string NombreComercial { get; set; }
        public string Descripcion { get; set; }
        public string Uso_terapeutico { get; set; }
        public double PrecioVenta { get; set; }
        public int Existencia { get; set; }
        public int Id_tipo { get; set; }
        public int Id_Rubro { get; set; }
        public int Id_presentacion { get; set; }
        public string Concentracion { get; set; }
        public string laboratorio { get; set; }
        public Nullable<bool> Reseta { get; set; }
        public bool Estado_producto { get; set; }
        public System.DateTime fecha_regitro { get; set; }
        public System.DateTime fecha_elaboracion { get; set; }
        public System.DateTime fecha_vencimiento { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Detalle_Compra> Detalle_Compra { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Detalle_dev_compra> Detalle_dev_compra { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Detalle_Venta> Detalle_Venta { get; set; }
        public virtual PresentacionProducto PresentacionProducto { get; set; }
        public virtual RubroProducto RubroProducto { get; set; }
        public virtual Tipo_producto Tipo_producto { get; set; }
    }
}
